build:
  image: teaci/msys64
  shell: mingw64
  pull: true
  commands:
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-x86_64-wxWidgets mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-openssl mingw-w64-x86_64-boost mingw-w64-x86_64-waf python3
    - waf configure build --release --color=yes
  environment:
    - CLICOLOR_FORCE=1
    - PYTHONUNBUFFERED=1
    - LANG=C.UTF-8
