build:
  image: teaci/msys32
  shell: mingw32
  pull: true
  commands:
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-i686-wxWidgets mingw-w64-i686-gcc mingw-w64-i686-pkg-config mingw-w64-i686-openssl mingw-w64-i686-boost mingw-w64-i686-waf python3
    - waf configure build --release --color=yes
  environment:
    - CLICOLOR_FORCE=1
    - PYTHONUNBUFFERED=1
    - LANG=C.UTF-8
