language: cpp
compiler:
- clang
os:
- linux
- osx
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wxmac; fi
addons:
  apt:
    packages:
    - libwxgtk3.0-dev
    - libboost-dev
script:
- ./waf configure build
